In [1]:
import torch

In [2]:
input = torch.arange(10)
input

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [4]:
logspace = torch.logspace(3, 10, steps=5)
logspace

tensor([1.0000e+03, 5.6234e+04, 3.1623e+06, 1.7783e+08, 1.0000e+10])

In [5]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])