In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time

In [4]:
x = torch.tensor([-0.05, 1.2, 3, 4, -15, 5, -4], dtype=torch.float32)
relu = nn.ReLU()
print(relu(x))

tensor([0.0000, 1.2000, 3.0000, 4.0000, 0.0000, 5.0000, 0.0000])


In [7]:
print(F.sigmoid(x))

tensor([4.8750e-01, 7.6852e-01, 9.5257e-01, 9.8201e-01, 3.0590e-07, 9.9331e-01,
        1.7986e-02])


In [8]:
print(F.tanh(x))

tensor([-0.0500,  0.8337,  0.9951,  0.9993, -1.0000,  0.9999, -0.9993])
